### ISSUE TITLE
[FEATURE] Add translations

### ISSUE THREAD

**Issue by AnadeOre** [Uklizdev/LaTeX-Guide#2]
**Add various translations, some possible languages:** 
- [x] English.
- [ ] Spanish.
- [ ] Portuguese.
- [ ] German.
- [ ] Hindi.

_Feel free to add any option!_

What to do:
1. Fork the repository and clone it in your computer.
1. Add a folder called "Guide-LanguajeName" with the same files in the "Guide folder", make all the translations there!
1. Add a README-LanguajeName.md and translate the [Readme](https://github.com/Uklizdev/LaTeX-Guide#readme)
1. Once you've finished you can make a PR to the master branch.

Remember to always [keep your fork updated](https://dev.to/giannellitech/keeping-your-fork-up-to-date-klh)!

**Comment by himanshu007-creator** [comment]
hi, i would like to do translations in HINDI, please guide me further to get started🔥

**Comment by AnadeOre** [comment]
That'd be great! to do the translations you can do the following:

Fork the repository and clone it in your computer.
Add a folder called "Guide-Hindi" with the same files in the "Guide folder", make all the translations there!
Add a README-Hindi.md and translate the [Readme](https://github.com/Uklizdev/LaTeX-Guide#readme)
Once you've finished you can make a PR to the master branch.

The things that need translation are the following:

- All the text in each guide file
- Readme file

If you have any questions now or while translating, post a comment here, I'll try to answer asap 😄
